# Generated by Django 5.2.9 on 2025-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_editor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
