# Generated by Django 5.2.9 on 2025-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("num_generations", models.IntegerField(default=1)),
                ("input_image", models.ImageField(upload_to="inputs/")),
                (
                    "input_mask",
                    models.ImageField(blank=True, null=True, upload_to="masks/"),
                ),
                ("output_dir", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
